### ISSUE TITLE
Simplify the CSS code for the font-weight property.

### ISSUE THREAD

**Issue by josephtkim** [Mister-D23/prj-rev-bwfs-dasmoto#5]
Great job simplifying the CSS code for the font-family property. You can also simplify it further for the font-weight property, which you can probably add to the html selector.

```css
html {
  font-family: Helvetica;
  font-weight: bold;
}
```
